### ISSUE TITLE
 transfer to posthtml org ?

### ISSUE THREAD

**Issue by Scrum** [metonym/posthtml-lint#9]
@metonym  Hi, if there is a desire, we can transfer all your posthtml packages to posthtml org

**Comment by metonym** [comment]
@Scrum I think this repo needs to be revisited before transferring. I saw your https://github.com/posthtml/posthtml-w3c and I think it's more thorough. What do you think can be done to improve this? Should the focus be on fixing "fixable" errors? (like in tslint)

**Comment by Scrum** [comment]
@metonym I think that any product is good in its own way, it will be found by the one to whom it suits more than other solutions and your products are no exception :)

We can move all your plugins related to posthtml, I believe that they all have the right to development.

Perhaps these solutions will lead to a merger and the creation of more interesting solutions.

In any case, all decisions should be improved; competition is a good factor in creating a good product.

**Comment by metonym** [comment]
@Scrum Great reply. I'll transfer when I get the chance (and the other repos, inline-favicon, noopener, noscript).

**Comment by Scrum** [comment]
@metonym transfered all you pkg, good day :)
